In [1]:
import os
import sys
import numpy as np
from collections import defaultdict

inputfilepath = 'C:\EMOLGUI\A_O_C\Day8.txt'

In [2]:
forest = []
with open(inputfilepath,'r') as f:
    for line in f:
        forest.append(list(line.rstrip()))

In [4]:
np_forest = np.array(forest)

In [6]:
visible_trees = np.zeros(np_forest.shape)

In [10]:
for row in range(np_forest.shape[0]):
    for column in range(np_forest.shape[1]):
        if row == 0 or column == 0 or row == np_forest.shape[0]-1 or column == np_forest.shape[1]-1:
            visible_trees[row,column] = 1
        else:
            height = np_forest[row,column]
            if height > min(max(np_forest[0:row,column]), max(np_forest[row,0:column]), max(np_forest[row+1:np_forest.shape[0],column]), max(np_forest[row,column+1:np_forest.shape[1]])):
                visible_trees[row,column] = 1

In [12]:
visible_trees, np_forest

(array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 0., ..., 0., 1., 1.],
        [1., 0., 1., ..., 0., 0., 1.],
        ...,
        [1., 1., 0., ..., 0., 0., 1.],
        [1., 0., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]),
 array([['2', '0', '1', ..., '0', '1', '1'],
        ['2', '2', '1', ..., '0', '2', '1'],
        ['1', '0', '2', ..., '0', '1', '2'],
        ...,
        ['0', '2', '1', ..., '1', '1', '2'],
        ['0', '0', '2', ..., '2', '2', '2'],
        ['1', '0', '0', ..., '1', '1', '0']], dtype='<U1'))

In [13]:
np.sum(visible_trees)

1782.0

#### QUESTION 2: Scenic score

In [36]:
scenicScore = np.zeros(np_forest.shape)

np_forest = np_forest.astype(int)

for row in range(1,np_forest.shape[0]-1):
    for column in range(1,np_forest.shape[1]-1):
        height = int(np_forest[row,column])
        up = np.flip(np_forest[0:row,column])
        down = np_forest[row+1:np_forest.shape[0]:1,column]
        left = np.flip(np_forest[row,0:column])
        right = np_forest[row,column+1:np_forest.shape[1]]

        if max(up) < height:
            score_up = len(up)
        else:
            score_up = np.min(np.where((up - height)>=0)) + 1
        if max(down) < height:
            score_down = len(down)
        else:
            score_down = np.min(np.where((down - height)>=0)) + 1
        if max(left) < height:
            score_left = len(left)
        else:
            score_left = np.min(np.where((left - height)>=0)) + 1
        if max(right) < height:
            score_right = len(right)
        else:
            score_right = np.min(np.where((right - height)>=0)) + 1
        
        scenicScore[row,column] = score_up*score_down*score_left*score_right

        # print(np_forest[:,column])
        # print(up)
        # print(down)

        # print(np_forest[row,:])
        # print(left)
        # print(right)

        #break
    #break

In [45]:
np.max(scenicScore)

474606.0

In [46]:
np.where(scenicScore == np.max(scenicScore))

(array([22], dtype=int64), array([47], dtype=int64))

In [48]:
scenicScore[22,47],np_forest[22,47], np_forest[22,:], np_forest[:,47]

(474606.0,
 8,
 array([4, 0, 0, 0, 1, 2, 2, 0, 1, 2, 3, 3, 3, 3, 5, 5, 4, 3, 4, 3, 6, 5,
        5, 5, 2, 4, 3, 2, 6, 7, 7, 6, 6, 5, 3, 3, 6, 3, 5, 3, 4, 4, 6, 3,
        6, 4, 4, 8, 7, 5, 5, 5, 4, 7, 7, 6, 7, 7, 6, 3, 5, 6, 4, 4, 6, 4,
        3, 5, 3, 4, 6, 5, 4, 2, 4, 4, 6, 6, 2, 3, 3, 5, 3, 4, 5, 4, 1, 5,
        3, 5, 1, 3, 4, 3, 3, 0, 2, 2, 3]),
 array([3, 4, 3, 2, 2, 4, 1, 2, 6, 2, 5, 4, 4, 6, 4, 3, 7, 6, 5, 4, 5, 3,
        8, 7, 5, 4, 5, 5, 5, 5, 6, 8, 5, 5, 6, 5, 6, 8, 9, 6, 8, 9, 8, 7,
        9, 9, 8, 9, 8, 8, 7, 8, 7, 9, 9, 9, 9, 9, 7, 6, 9, 6, 8, 7, 6, 9,
        7, 9, 9, 8, 6, 9, 5, 7, 8, 7, 8, 5, 5, 5, 5, 4, 4, 5, 3, 3, 3, 2,
        2, 4, 5, 6, 6, 5, 5, 5, 3, 4, 4]))

In [51]:
47 * 51 * 22 * 9 

474606